# Generated by Django 4.2.7 on 2023-11-01 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FastenerSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.gradeclass')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.itemmaterial')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.fastenersize')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandardCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.standard')),
            ],
        ),
        migrations.CreateModel(
            name='OrderNut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('nut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.nut')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBolt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('bolt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bolt')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.orderstatus'),
        ),
        migrations.AddField(
            model_name='nut',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.standardcode'),
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.itemcategory')),
            ],
        ),
        migrations.AddField(
            model_name='bolt',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.gradeclass'),
        ),
        migrations.AddField(
            model_name='bolt',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.itemmaterial'),
        ),
        migrations.AddField(
            model_name='bolt',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.fastenersize'),
        ),
        migrations.AddField(
            model_name='bolt',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.standardcode'),
        ),
        migrations.AlterUniqueTogether(
            name='nut',
            unique_together={('standard', 'material', 'size', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='bolt',
            unique_together={('size', 'standard', 'length', 'material', 'grade')},
        ),
    ]
