# Generated by Django 4.2.7 on 2023-11-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='invoice',
            field=models.URLField(blank=True),
        ),
    ]
