# Generated by Django 4.2.7 on 2023-11-06 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_orderitem_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDataSetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='google_sheet_link',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ImportDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateField(auto_now_add=True)),
                ('import_time', models.TimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('google_sheet_link', models.URLField(blank=True, max_length=255)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.importdatasetstatus')),
            ],
        ),
    ]
