# Generated by Django 4.2.7 on 2023-11-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_generalitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('table_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='generalitem',
            name='additional_fields',
        ),
        migrations.AddField(
            model_name='generalitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generalitem',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='accounting.attribute'),
        ),
    ]
