# Generated by Django 4.2.7 on 2023-11-06 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_importdatasetstatus_order_google_sheet_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.importdataset')),
            ],
        ),
    ]
