# Generated by Django 4.2.7 on 2023-11-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_attribute_item_remove_generalitem_additional_fields_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('object_id', 'table_name')},
        ),
    ]
