# Generated by Django 4.2.7 on 2023-11-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_importdate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importdate',
            unique_together={('data_set', 'data')},
        ),
    ]
