# Generated by Django 4.2.7 on 2023-11-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_importdate_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportDate',
            new_name='ImportData',
        ),
        migrations.AlterField(
            model_name='importdataset',
            name='google_sheet_link',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='importdatasetstatus',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
