# Generated by Django 4.2.7 on 2023-11-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.item')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.place')),
            ],
        ),
    ]
