# Generated by Django 4.2.7 on 2023-11-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_itemplacequantity_warehouse_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseactiontype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
