# Generated by Django 4.2.7 on 2023-11-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_warehouseactiontype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemplacequantity',
            name='warehouse_flow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.warehouseflow'),
            preserve_default=False,
        ),
    ]
