# Generated by Django 4.2.7 on 2023-11-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_importdataset_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.itemcategory'),
        ),
    ]
