# Generated by Django 4.2.7 on 2023-11-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_placetype_supplier_place_type_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderBolt',
        ),
    ]
