# Generated by Django 4.2.7 on 2023-11-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalitem',
            name='category',
        ),
    ]
