# Generated by Django 4.2.7 on 2023-11-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_delete_orderbolt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderNut',
        ),
    ]
