# Generated by Django 4.2.7 on 2023-11-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_remove_item_category_generalitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemplace',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
