# Generated by Django 4.2.7 on 2023-11-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_shoppingcart_shoppingcartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcartitem',
            old_name='invoice',
            new_name='invoice_link',
        ),
    ]
