# Generated by Django 4.2.7 on 2023-11-13 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0019_rename_invoice_shoppingcartitem_invoice_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='created_by',
            field=models.ForeignKey(help_text='Поки це додаткова опція, це поле буде запонюватись автоматично', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='google_sheet_link',
            field=models.URLField(blank=True, help_text='Якщо добавити посилання - програма спробує автоматично згенерувати всі компоненти та добавити в корзину', max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='purpose',
            field=models.CharField(help_text='Необхідно коротко описати призначення даного замовлення.', max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('completed', 'Completed')], default='draft', help_text='Статус впливає як будуть оброблятись дані. Draft: це як шаблон, програма створює записи для кожного компоненти та саму корзину. Approved: замовлення сформовано та на етапі оформлення. Completed: всі комопненти доставленні, програма генерує для них записи, які відповідають реальному місцезнашодженню та кількості', max_length=20),
        ),
    ]
