# Generated by Django 4.2.7 on 2023-11-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_shoppingcartitem_storage_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardcode',
            name='standard',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Standard',
        ),
    ]
