# Generated by Django 4.2.7 on 2023-11-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_alter_standardcode_standard_delete_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='H:\\EngineeringStudioService\\Images'),
        ),
    ]
